// Generated by 'unplugin-auto-import'
export {}
declare global {
  const css: typeof import("@emotion/react")["css"]
  const keyframes: typeof import("@emotion/react")["keyframes"]
  const styled: typeof import("@emotion/styled")["default"]
}
