#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

exec 1> /dev/tty

echo ""
echo "✨ Styling your project before committing."
echo "⏱️ Please be patient, this may take a while..."
echo ""

npx lint-staged ||
(
    echo ""
    echo "🧙‍♂️ This code shall not pass!"
    echo "❌ Fix the errors and try to commit again."
    echo "💡 Hint: Validate your changes with 'npm run lint'."
    echo ""
    false
)

echo ""
echo "🎉 No error found!"
echo "🚀 Your changes are being commited now."
echo ""
